// Real seed content sourced from the BIX company brochure (2025 update).
// Used to populate the dynamic collections defined in the SRS: services,
// equipment, gallery, projects, training.

const services = [
  {
    title: "Radiography Testing (X-Ray & Gamma Ray)",
    category: "Non-Destructive Testing",
    shortDescription:
      "Uses X-Ray or Gamma Ray sources to view internal structure and detect flaws with a permanent record of inspection.",
    introduction:
      "Radiographic Testing (RT) uses X-Ray or Gamma Ray (Ir-192) sources to view and assess the internal structure of an asset. RT is sensitive to corrosion, changes in thickness, voids, cracks and material density changes, and can detect both surface and sub-surface defects with minimum surface preparation.",
    detailedDescription:
      "In Radiography Testing the test-part is placed between the radiation source and film. The material density and thickness differences of the test-part will attenuate radiation and are then recorded on film. BIX staff are qualified, certified, and highly experienced using X-ray and gamma ray devices, producing high quality radiographs according to international codes and standards, while operating within strict health and safety parameters.",
    workingProcess: [
      { title: "Site Survey & Safety Zoning", description: "Radiation zone marked and cleared per BAERA safety protocol." },
      { title: "Source/Film Placement", description: "Test-part placed between radiation source and film/detector." },
      { title: "Exposure", description: "Controlled exposure captures material density and thickness variations." },
      { title: "Film/Digital Processing", description: "Radiograph developed or digitally rendered for evaluation." },
      { title: "Interpretation & Reporting", description: "Certified interpreter evaluates against applicable code and issues report." },
    ],
    features: ["Largest fleet of Pipeline X-Ray Crawlers in Bangladesh", "ASNT-certified radiographers", "Digital and film radiography options"],
    benefits: ["Accurately locates, sizes and identifies defects", "Provides a permanent record of the inspection", "Detects both surface and sub-surface defects"],
    image: "/images/services/radiography.jpg",
    bannerImage: "/images/services/radiography-banner.jpg",
    published: true,
  },
  {
    title: "Ultrasonic Testing (UT)",
    category: "Non-Destructive Testing",
    shortDescription: "Detects surface and sub-surface discontinuities, corrosion and cracks using ultrasonic waves.",
    introduction:
      "Conventional Ultrasonic Testing (UT) is a commonly-used non-destructive testing technique that measures the propagation of ultrasonic waves through a material to examine properties, measure thickness and detect discontinuities.",
    detailedDescription:
      "UT is used to detect surface and sub-surface defects and supply accurate readings regarding discontinuity size and shape, including corrosion, erosion, flaws and cracks.",
    workingProcess: [
      { title: "Surface Preparation", description: "Test surface cleaned and couplant applied." },
      { title: "Probe Calibration", description: "Equipment calibrated against reference standards." },
      { title: "Scanning", description: "Probe scanned across the test area to capture wave reflections." },
      { title: "Data Evaluation", description: "Signal amplitude and position analyzed against acceptance criteria." },
      { title: "Reporting", description: "Certified technician issues inspection report." },
    ],
    features: ["Portable, fast on-site inspection", "High accuracy discontinuity sizing", "Certified NDE Level II technicians"],
    benefits: ["No radiation hazard", "Detects defects not visible on the surface", "Cost-effective for large assets"],
    image: "/images/services/ultrasonic.jpg",
    bannerImage: "/images/services/ultrasonic-banner.jpg",
    published: true,
  },
  {
    title: "Ultrasonic Thickness Gauging (UTG)",
    category: "Non-Destructive Testing",
    shortDescription: "Accurate wall-thickness measurement for corrosion monitoring on pipes, plates and vessels.",
    introduction:
      "Ultrasonic Thickness Gauging is used to measure the remaining wall thickness of pipes, tanks, and pressure vessels to monitor corrosion and erosion over time.",
    detailedDescription:
      "Using calibrated ultrasonic thickness gauges, BIX technicians provide precise point and grid thickness readings, helping clients track corrosion rates and plan maintenance or replacement.",
    workingProcess: [
      { title: "Grid Marking", description: "Inspection points marked on the asset per client requirement." },
      { title: "Calibration", description: "Gauge calibrated on a known-thickness reference block." },
      { title: "Measurement", description: "Thickness readings taken at each grid point." },
      { title: "Reporting", description: "Corrosion mapping report generated with readings." },
    ],
    features: ["Portable digital gauges", "Grid and point measurement", "Trend analysis support"],
    benefits: ["Early corrosion detection", "Supports Remaining Life Assessment", "Minimal surface preparation"],
    image: "/images/services/utg.jpg",
    bannerImage: "/images/services/utg-banner.jpg",
    published: true,
  },
  {
    title: "Magnetic Particle Inspection (MPI)",
    category: "Non-Destructive Testing",
    shortDescription: "Quick, cost-effective method to detect surface and near-surface discontinuities.",
    introduction:
      "Magnetic Particle Testing is a quick, cost-effective NDT inspection method to detect surface and near-surface discontinuities in ferromagnetic materials.",
    detailedDescription:
      "In MT, the ferromagnetic material is magnetized and finely-milled iron particles coated with a dye pigment are applied. The particles cluster directly over discontinuities, which can be visually detected under proper lighting conditions.",
    workingProcess: [
      { title: "Surface Preparation", description: "Test surface cleaned of dirt, grease and scale." },
      { title: "Magnetization", description: "Ferromagnetic material magnetized using yoke or prod." },
      { title: "Particle Application", description: "Iron particles with dye pigment applied to the surface." },
      { title: "Inspection", description: "Surface examined under proper lighting for particle clustering." },
      { title: "Demagnetization & Reporting", description: "Part demagnetized where required and report issued." },
    ],
    features: ["Portable electromagnetic yokes", "Fast turnaround", "Effective on welds and castings"],
    benefits: ["Detects surface and near-surface flaws", "Low cost", "Immediate visual results"],
    image: "/images/services/mpi.jpg",
    bannerImage: "/images/services/mpi-banner.jpg",
    published: true,
  },
  {
    title: "Dye Penetrant Testing (DPT)",
    category: "Non-Destructive Testing",
    shortDescription: "Low-cost method for finding surface-breaking discontinuities on smooth, nonporous surfaces.",
    introduction:
      "Penetrant Testing (PT) is a non-destructive method used for finding surface-breaking discontinuities on relatively smooth, nonporous surfaces.",
    detailedDescription:
      "It is a low-cost technique that can inspect complex geometries easily. Assets do not have to be disassembled or removed from the facility for inspection, making the process quick and efficient.",
    workingProcess: [
      { title: "Surface Cleaning", description: "Surface cleaned and dried thoroughly." },
      { title: "Penetrant Application", description: "Dye penetrant applied and given dwell time to seep into flaws." },
      { title: "Excess Removal", description: "Excess penetrant removed from the surface." },
      { title: "Developer Application", description: "Developer applied to draw penetrant out of discontinuities." },
      { title: "Inspection & Reporting", description: "Indications examined and documented in a report." },
    ],
    features: ["Works on complex geometries", "No power source required", "Fast on-site results"],
    benefits: ["Low cost", "No disassembly needed", "Effective for welds and castings"],
    image: "/images/services/dpt.jpg",
    bannerImage: "/images/services/dpt-banner.jpg",
    published: true,
  },
  {
    title: "Phased Array Ultrasonic Testing (PAUT)",
    category: "Advanced Non-Destructive Testing",
    shortDescription: "Computer-controlled ultrasonic beam array for fast, highly efficient weld defect detection.",
    introduction:
      "Phased Array Ultrasonic Testing (PAUT) is an advanced method of ultrasonic testing, widely used in construction, pipelines and power generation to detect discontinuities, cracks or flaws.",
    detailedDescription:
      "A PAUT array is more robust and easier to use than conventional single-element probes, capturing hundreds of signals at once and reducing false alarms. It provides a permanent record and can detect defects at the surface and into the volume of a weld with no dead zone, also giving lateral position information (depth and height). Instruments used: OMNISCAN SX, PRISMA and PHASCON.",
    workingProcess: [
      { title: "Procedure Qualification", description: "Scan plan developed and qualified per applicable code." },
      { title: "Probe Setup", description: "Phased array probe and wedge configured on the instrument." },
      { title: "Scanning", description: "Weld or component scanned with electronically steered beams." },
      { title: "Data Analysis", description: "Sectorial and linear scans analyzed for indications." },
      { title: "Reporting", description: "Permanent digital record and inspection report issued." },
    ],
    features: ["Multiple simultaneous sound beam angles", "Corrosion mapping capability", "Permanent digital record"],
    benefits: ["Faster inspection than conventional UT", "Reduced false alarms", "Accurate defect sizing and positioning"],
    image: "/images/services/paut.jpg",
    bannerImage: "/images/services/paut-banner.jpg",
    published: true,
  },
  {
    title: "Long Range Ultrasonic Testing (LRUT)",
    category: "Advanced Non-Destructive Testing",
    shortDescription: "Remotely analyzes assets for corrosion and flaws over long distances with minimal insulation removal.",
    introduction:
      "LRUT is used to remotely analyze pipelines, piping systems and other assets for corrosion and flaws over long distances without the need for direct contact along the entire length.",
    detailedDescription:
      "LRUT is used to rapidly inspect pipelines and piping systems with minimal insulation removal, quickly localizing cracking and corrosion damage to pinpoint and characterize length and depth.",
    workingProcess: [
      { title: "Collar Installation", description: "Transducer collar fitted around the pipe at the test location." },
      { title: "Wave Propagation", description: "Guided ultrasonic waves sent along the pipe wall." },
      { title: "Signal Capture", description: "Reflected signals captured from changes in cross-section." },
      { title: "Analysis", description: "Signals analyzed to locate and estimate severity of anomalies." },
    ],
    features: ["Minimal insulation removal", "Long inspection range per test point", "Ideal for buried or insulated pipe"],
    benefits: ["Rapid screening of long pipe runs", "Reduced inspection cost and downtime", "Early corrosion localization"],
    image: "/images/services/lrut.jpg",
    bannerImage: "/images/services/lrut-banner.jpg",
    published: true,
  },
  {
    title: "Digital Radiography Testing",
    category: "Advanced Non-Destructive Testing",
    shortDescription: "Digital detector-based radiography with shorter exposure time and higher contrast imaging.",
    introduction:
      "Digital radiography is an advanced technology based on digital detector systems instead of film, where the image is displayed directly on a computer screen without developing chemicals.",
    detailedDescription:
      "Advantages over conventional radiography include shorter exposure time, no chemical evaluation needed, and better-quality, higher contrast images.",
    workingProcess: [
      { title: "Setup", description: "Digital detector positioned against the test-part." },
      { title: "Exposure", description: "Controlled radiation exposure captured directly by the detector." },
      { title: "Digital Rendering", description: "Image rendered instantly on a computer screen." },
      { title: "Interpretation & Reporting", description: "Certified interpreter reviews image and issues report." },
    ],
    features: ["No film processing chemicals required", "Instant image review", "Higher contrast than conventional film"],
    benefits: ["Faster turnaround", "Lower consumable cost over time", "Easy digital archiving"],
    image: "/images/services/digital-radiography.jpg",
    bannerImage: "/images/services/digital-radiography-banner.jpg",
    published: true,
  },
  {
    title: "Positive Material Identification (PMI)",
    category: "Advanced Non-Destructive Testing",
    shortDescription: "Specialized method for identifying the composition and alloy grade of components and materials.",
    introduction:
      "Positive Material Identification is a specialized non-destructive testing method for identifying the composition of components and materials, providing information on the metal grade and alloy composition.",
    detailedDescription:
      "The mechanical integrity of safety-critical plant depends on the correct materials being used for vessels, piping, valves and pumps. If incorrect material is used, design assumptions become invalid and components may fail due to lower strength or poor corrosion resistance.",
    workingProcess: [
      { title: "Surface Preparation", description: "Test spot cleaned of coating, scale or paint." },
      { title: "Analyzer Reading", description: "Handheld analyzer measures alloy composition at the test spot." },
      { title: "Grade Verification", description: "Result compared against expected material specification." },
      { title: "Reporting", description: "Material grade report issued per component tested." },
    ],
    features: ["Handheld portable analyzers", "Non-destructive alloy verification", "Fast on-site results"],
    benefits: ["Prevents material mix-up failures", "Verifies compliance with design specification", "Supports Risk Based Inspection programs"],
    image: "/images/services/pmi.jpg",
    bannerImage: "/images/services/pmi-banner.jpg",
    published: true,
  },
  {
    title: "Lifting Equipment Inspection",
    category: "Inspection Services",
    shortDescription: "Thorough examination and testing of lifting equipment to ensure it is fit for use.",
    introduction:
      "BIX specializes in thorough examination and testing of lifting equipment to ensure it is fit for use in accordance with British Standard or other International Standards.",
    detailedDescription:
      "Our specialist team is highly trained in inspecting all types of lifting accessories and equipment, ensuring the minimum safety requirements are met. Examination can range from visual inspection, NDT inspection, function testing, to load testing. Once an item passes inspection, a Report of Thorough Examination is produced. Any deficiencies found are documented, and once corrected, proper tests and certificates are issued.",
    workingProcess: [
      { title: "Visual Inspection", description: "General condition and identification markings checked." },
      { title: "NDT Inspection", description: "Critical areas examined using MPI/DPT as required." },
      { title: "Function/Load Testing", description: "Equipment tested under function or rated load conditions." },
      { title: "Certification", description: "Report of Thorough Examination and certificate issued." },
    ],
    features: ["Covers cranes, slings, hooks and rigging", "Compliant with British/International Standards", "Detailed deficiency reporting"],
    benefits: ["Ensures workplace safety compliance", "Reduces risk of lifting equipment failure", "Supports insurance and audit requirements"],
    image: "/images/services/lifting-equipment.jpg",
    bannerImage: "/images/services/lifting-equipment-banner.jpg",
    published: true,
  },
  {
    title: "Welding & Painting Inspection",
    category: "Inspection Services",
    shortDescription: "Third-party welding inspection and coating inspection to project specification.",
    introduction:
      "BIX has highly trained, AWS Certified Welding Inspectors (CWI) available to customers in the refining, petrochemical, oil & gas and power industries, along with qualified painting and coating inspectors.",
    detailedDescription:
      "Welding inspection services include review of WPS and PQR, witnessing Procedure Qualification Records and Welder Performance Qualification, and independent third-party inspection reporting. Our painting inspectors judge site conditions, recommend suitable coatings for corrosive environments, and verify the painting process follows project requirements.",
    workingProcess: [
      { title: "Document Review", description: "WPS/PQR reviewed against applicable codes and standards." },
      { title: "Witness Testing", description: "PQR and WPQ witnessed by certified inspector." },
      { title: "In-Process Inspection", description: "Welding or coating process inspected during execution." },
      { title: "Final Reporting", description: "Independent inspection report issued to client." },
    ],
    features: ["AWS Certified Welding Inspectors (CWI)", "Independent third-party reporting", "Coating condition assessment"],
    benefits: ["Ensures weld quality and code compliance", "Protects assets from corrosion", "Reduces rework and warranty risk"],
    image: "/images/services/welding-painting.jpg",
    bannerImage: "/images/services/welding-painting-banner.jpg",
    published: true,
  },
  {
    title: "Rope Access Services",
    category: "Inspection Services",
    shortDescription: "IRATA-certified rope access techniques for inspection in hard-to-reach locations.",
    introduction:
      "Rope access techniques enable execution of jobs that cannot be performed with traditional access methods, drastically reducing cost while maintaining the highest safety standards.",
    detailedDescription:
      "BIX rope access members are IRATA-qualified professionals operating under the IRATA International Code of Practice, with equipment constantly maintained and inspected. Rope access minimizes interference with other activities and reduces the time needed for maintenance stops. Services include NDT & Inspection, Hull Inspection and Class Surveys, Lifting Equipment Inspection, and Painting & Coating Inspection.",
    workingProcess: [
      { title: "Access Planning", description: "Rope access route and rescue plan prepared per IRATA guidelines." },
      { title: "Rigging", description: "Ropes and safety systems rigged by certified technicians." },
      { title: "Inspection Work", description: "NDT, visual or coating inspection performed at height/depth." },
      { title: "Reporting", description: "Findings documented and reported to client." },
    ],
    features: ["IRATA certified technicians", "Reduced scaffolding cost and time", "Access to confined and elevated areas"],
    benefits: ["Minimizes operational downtime", "High safety standard compliance", "Cost-effective versus traditional access"],
    image: "/images/services/rope-access.jpg",
    bannerImage: "/images/services/rope-access-banner.jpg",
    published: true,
  },
];

const equipment = [
  {
    name: "Gamma Ray Machine — Sigma 880",
    shortDescription: "Gamma radiography camera used for pipeline and industrial radiographic testing.",
    description: "The Sigma 880 gamma ray camera from QSA Global Inc, USA, is used extensively by BIX for pipeline and structural radiography, offering reliable Ir-192 source handling for field inspections.",
    manufacturer: "QSA Global Inc, USA",
    model: "Sigma 880",
    quantity: "01 Set",
    category: "Radiographic Testing",
    specifications: [{ label: "Type", value: "Gamma Ray Camera" }, { label: "Isotope", value: "Ir-192" }],
    features: ["Rugged field-ready housing", "Compatible with standard Ir-192 sources"],
    image: "/images/equipment/gamma-ray-sigma-880.jpg",
  },
  {
    name: "Gamma Ray Machine — Delta 880",
    shortDescription: "Fleet of gamma radiography cameras for high-volume pipeline radiography.",
    description: "5 sets of Delta 880 gamma ray cameras from QSA Global Inc, USA, forming part of BIX's large gamma radiography fleet used on major gas transmission pipeline projects across Bangladesh.",
    manufacturer: "QSA Global Inc, USA",
    model: "Delta 880",
    quantity: "05 Sets",
    category: "Radiographic Testing",
    specifications: [{ label: "Type", value: "Gamma Ray Camera" }, { label: "Isotope", value: "Ir-192" }],
    features: ["High-volume pipeline radiography", "Field-proven reliability"],
    image: "/images/equipment/gamma-ray-delta-880.jpg",
  },
  {
    name: "X-Ray Machine — XXG-3505 (350KV)",
    shortDescription: "350KV, 5mA portable industrial X-ray flaw detector.",
    description: "Portable external X-ray machine manufactured by Dandong Zhongyi Electronic Co. Ltd., China, rated at 350KV / 5mA, used for high-penetration radiography of thick-walled pipelines and vessels.",
    manufacturer: "Dandong Zhongyi Electronic Co. Ltd., China",
    model: "XXG-3505",
    quantity: "14 Sets",
    category: "Radiographic Testing",
    specifications: [{ label: "Voltage", value: "350 KV" }, { label: "Current", value: "5 mAmp" }],
    features: ["High penetration capability", "Portable field unit"],
    image: "/images/equipment/xray-xxg-3505.jpg",
  },
  {
    name: "Ultrasonic Phased Array — OMNISCAN SX",
    shortDescription: "Advanced phased array flaw detector used for PAUT and TOFD inspection.",
    description: "The OMNISCAN SX from Olympus NDT, Canada, is used by BIX for advanced Phased Array Ultrasonic Testing and TOFD, delivering fast, highly efficient weld defect detection with a permanent digital record.",
    manufacturer: "Olympus NDT, Canada",
    model: "OMNISCAN SX (Serial# QC-015432)",
    quantity: "01 Set",
    category: "Advanced Ultrasonic Testing",
    specifications: [{ label: "Type", value: "Phased Array Flaw Detector" }],
    features: ["Sectorial and linear scanning", "Corrosion mapping capable"],
    image: "/images/equipment/paut-omniscan-sx.jpg",
  },
  {
    name: "Ultrasonic Phased Array — PRISMA",
    shortDescription: "Phased array instrument used for advanced weld inspection.",
    description: "Prisma phased array unit from Sonatest, UK (Serial# 1010532), used for PAUT inspection of welds in pipeline, power and structural projects.",
    manufacturer: "Sonatest, UK",
    model: "Prisma",
    quantity: "01 Set",
    category: "Advanced Ultrasonic Testing",
    specifications: [{ label: "Type", value: "Phased Array Instrument" }],
    features: ["Compact field-ready design"],
    image: "/images/equipment/paut-prisma.jpg",
  },
  {
    name: "Ultrasonic Flaw Detector — EPOCH 6LT",
    shortDescription: "Conventional ultrasonic flaw detector for weld and material inspection.",
    description: "EPOCH 6LT from Olympus Scientific Solutions, America (Serial# 210209901), used for conventional ultrasonic flaw detection across various industrial inspection projects.",
    manufacturer: "Olympus Scientific Solutions, USA",
    model: "EPOCH 6LT",
    quantity: "01 Set",
    category: "Ultrasonic Testing",
    specifications: [{ label: "Type", value: "Ultrasonic Flaw Detector" }],
    features: ["Portable, rugged design", "Wide probe compatibility"],
    image: "/images/equipment/ut-epoch-6lt.jpg",
  },
  {
    name: "Ultrasonic Thickness Gauge — 38DL Plus",
    shortDescription: "Precision digital thickness gauge for corrosion monitoring.",
    description: "38DL Plus thickness gauges from Olympus, USA, used for accurate wall thickness measurement and corrosion mapping on pipes, plates and pressure vessels.",
    manufacturer: "Olympus, USA",
    model: "38DL Plus",
    quantity: "03 Sets",
    category: "Ultrasonic Thickness Gauging",
    specifications: [{ label: "Type", value: "Digital Thickness Gauge" }],
    features: ["High accuracy readings", "Data logging capability"],
    image: "/images/equipment/utg-38dl-plus.jpg",
  },
  {
    name: "Electromagnetic Yoke — B310S (230V)",
    shortDescription: "Portable electromagnetic yoke for magnetic particle inspection.",
    description: "B310S electromagnetic yoke from Parker Research Corp., USA, used for magnetic particle inspection of welds and ferromagnetic components on-site.",
    manufacturer: "Parker Research Corp., USA",
    model: "B310S",
    quantity: "02 Sets",
    category: "Magnetic Particle Inspection",
    specifications: [{ label: "Voltage", value: "230 V" }],
    features: ["Portable field unit", "High lifting power"],
    image: "/images/equipment/mpi-yoke-b310s.jpg",
  },
  {
    name: "Hardness Tester — MH310",
    shortDescription: "Portable Leeb hardness tester for on-site material verification.",
    description: "MH310 portable hardness testers from LEEB, China, used to determine material characteristics such as strength, ductility and wear resistance, and to verify heat treatment processes.",
    manufacturer: "LEEB, China",
    model: "MH310",
    quantity: "05 Sets",
    category: "Hardness Testing",
    specifications: [{ label: "Type", value: "Portable Hardness Tester" }],
    features: ["On-site material verification", "Verifies heat treatment quality"],
    image: "/images/equipment/hardness-mh310.jpg",
  },
  {
    name: "PWHT Machine — EHS-91-6 (6 Channel)",
    shortDescription: "Automatic 6-channel resistance-type Post Weld Heat Treatment machine.",
    description: "Automatic 6-channel PWHT machine from Hotfoil-EHS, USA, with complete accessories, used for controlled post-weld heat treatment to relieve residual stress and reduce cracking risk.",
    manufacturer: "Hotfoil-EHS, USA",
    model: "EHS-91-6",
    quantity: "01 Set",
    category: "Post Weld Heat Treatment",
    specifications: [{ label: "Channels", value: "6" }, { label: "Type", value: "Resistance" }],
    features: ["Automatic temperature control", "Complete accessory set"],
    image: "/images/equipment/pwht-ehs-91-6.jpg",
  },
  {
    name: "Radiation Survey Meter — RDS 110",
    shortDescription: "Radiation survey meter for radiography site safety monitoring.",
    description: "RDS 110 survey meters from Rados Technology, Finland, used to monitor radiation levels and enforce safety zoning during radiographic testing operations per BAERA requirements.",
    manufacturer: "Rados Technology, Finland",
    model: "RDS 110",
    quantity: "02 Sets",
    category: "Radiation Safety",
    specifications: [{ label: "Type", value: "Radiation Survey Meter" }],
    features: ["Site safety compliance", "Real-time dose rate monitoring"],
    image: "/images/equipment/survey-meter-rds-110.jpg",
  },
  {
    name: "Portable Metallurgical Microscope",
    shortDescription: "Portable microscope for in-situ metallurgical inspection.",
    description: "Portable Metallurgical Microscope with complete accessories from Metkon Instruments Inc., Turkey, offering 100x-800x magnification for in-situ metallurgical inspection and replica examination.",
    manufacturer: "Metkon Instruments Inc., Turkey",
    model: "MOBISCOPE",
    quantity: "01 Set",
    category: "Metallurgical Inspection",
    specifications: [{ label: "Magnification", value: "100x - 800x" }],
    features: ["Coaxial illumination with rechargeable LED", "Polarizing kit included"],
    image: "/images/equipment/metallurgical-microscope.jpg",
  },
];

const projects = [
  {
    projectName: "42\" OD X 1000 PSIG Gas Transmission Pipeline — Bakhrabad-Meghnaghat-Haripur (Section-A)",
    clientName: "Gas Transmission Company Ltd (GTCL)",
    contractorName: "Castle Construction Co. Ltd.",
    location: "Bakhrabad to Kathalia River, Bangladesh",
    summary: "NDT services for approx. 16 km of 42\" OD X 1000 PSIG gas transmission pipeline from Bakhrabad Pig Launcher Station to the east side of Kathalia River.",
    workCategory: "Radiography by Using X-Ray Crawler & Gamma Ray",
    yearOfExecution: "Ongoing",
    images: ["/images/projects/pipeline-1.jpg"],
  },
  {
    projectName: "32.50 Km Gas Transmission Pipeline — Boalmari to Jahidpur (Section-B)",
    clientName: "Gas Transmission Company Ltd (GTCL)",
    contractorName: "Gasmin – Libra JV",
    location: "Boalmari, Shibganj, Bogura to Jahidpur, Pirganj, Rangpur",
    summary: "Construction of 32.50 Km long x 30\" OD x 1000 PSIG gas transmission pipeline under the Bogura-Rangpur-Saidpur Gas Transmission Pipeline project.",
    workCategory: "Radiography by Using X-Ray Crawler & Gamma Ray",
    yearOfExecution: "2021-2022",
    images: ["/images/projects/pipeline-2.jpg"],
  },
  {
    projectName: "Matarbari 2X600MW Ultra Super Critical Coal Fired Power Plant",
    clientName: "BPDB",
    contractorName: "Jurong Engineering Limited",
    location: "Matarbari, Bangladesh",
    summary: "NDT inspection services including RT, MT, PT, UT, PAUT and PWHT for the Matarbari ultra super critical coal fired power plant project.",
    workCategory: "RT, MT, PT, UT, PAUT, PWHT",
    yearOfExecution: "2021-2023",
    images: ["/images/projects/power-plant-1.jpg"],
  },
  {
    projectName: "Kafco Turnaround — 2022",
    clientName: "Karnafuli Fertilizer Company Ltd. (Kafco)",
    contractorName: "Karnafuli Fertilizer Company Ltd.",
    location: "Chittagong, Bangladesh",
    summary: "Provided radiography, magnetic particle, dye penetrant testing and PWHT services during the scheduled turnaround of the Kafco fertilizer plant.",
    workCategory: "RT, MPI, DPT, PWHT",
    yearOfExecution: "2022",
    images: ["/images/projects/kafco-turnaround.jpg"],
  },
  {
    projectName: "23m Dia LPG Tank — JMI Industrial Gas Ltd.",
    clientName: "JMI Industrial Gas Ltd.",
    contractorName: "Spectech India",
    location: "Barobkunda, Chittagong",
    summary: "NDT inspection of 2 nos. 23m diameter x 45mm & 63mm thick LPG storage tanks including PAUT, RT, MT and PT.",
    workCategory: "PAUT, RT, MT, PT",
    yearOfExecution: "2022-2024",
    images: ["/images/projects/lpg-tank.jpg"],
  },
  {
    projectName: "Bangabandhu Sheikh Mujib Railway Bridge Construction (WD-1)",
    clientName: "OTJ Joint Venture",
    contractorName: "OTJ Joint Venture",
    location: "Bangladesh",
    summary: "Ultrasonic testing services for the Bangabandhu Sheikh Mujib Railway Bridge construction project, including phased array inspection of flash butt and thermite welded rail joints.",
    workCategory: "Ultrasonic Test, Ultrasonic Phased Array",
    yearOfExecution: "2021-2024",
    images: ["/images/projects/railway-bridge.jpg"],
  },
  {
    projectName: "M.V. Banglar Shampad",
    clientName: "Bangladesh Shipping Corporation",
    contractorName: "Bangladesh Shipping Corporation",
    location: "Chittagong, Bangladesh",
    summary: "Radiographic and ultrasonic testing services for M.V. Banglar Shampad under class survey by Lloyd's Register Shipping.",
    workCategory: "Radiographic Test, Ultrasonic Test",
    yearOfExecution: "N/A",
    images: ["/images/projects/marine-vessel.jpg"],
  },
  {
    projectName: "Remaining Life Assessment — LPG Spheres, PTM & Reforming Unit",
    clientName: "Eastern Refinery Ltd (ERL)",
    contractorName: "Eastern Refinery Ltd (ERL)",
    location: "Chittagong, Bangladesh",
    summary: "Engineering inspection and remaining life assessment of LPG spheres, PTM and the reforming unit, including in-situ metallography and boroscope testing.",
    workCategory: "VI, MT, PT, UTG, HT, In-situ metallography, Boroscope Test",
    yearOfExecution: "2020-2021",
    images: ["/images/projects/erl-assessment.jpg"],
  },
];

const gallery = [
  {
    title: "Radiographic Testing on Gas Transmission Pipeline",
    image: "/images/gallery/gallery-1.jpg",
    description: "Field radiography using X-Ray crawler on a cross-country gas transmission pipeline.",
    projectName: "Bakhrabad-Meghnaghat-Haripur Gas Transmission Pipeline",
    date: new Date("2024-03-15"),
  },
  {
    title: "Phased Array Ultrasonic Inspection of Weld Joint",
    image: "/images/gallery/gallery-2.jpg",
    description: "PAUT inspection being carried out on a structural weld joint using OMNISCAN SX.",
    projectName: "Matarbari Power Plant",
    date: new Date("2023-06-10"),
  },
  {
    title: "Magnetic Particle Inspection of Drilling Equipment",
    image: "/images/gallery/gallery-3.jpg",
    description: "MPI being performed on drilling tools and accessories at a rig site.",
    projectName: "Different Drilling Tools Inspection",
    date: new Date("2022-11-02"),
  },
  {
    title: "Post Weld Heat Treatment of LPG Sphere",
    image: "/images/gallery/gallery-4.jpg",
    description: "PWHT operation on an LPG storage sphere shell weld.",
    projectName: "LPG Sphere Project",
    date: new Date("2021-09-20"),
  },
  {
    title: "Rope Access Hull Inspection",
    image: "/images/gallery/gallery-5.jpg",
    description: "IRATA-certified technician performing rope access hull inspection on a marine vessel.",
    projectName: "Marine Hull Inspection",
    date: new Date("2025-01-18"),
  },
  {
    title: "Ultrasonic Thickness Gauging on Storage Tank",
    image: "/images/gallery/gallery-6.jpg",
    description: "Grid thickness measurement being taken on a storage tank shell for corrosion monitoring.",
    projectName: "Storage Tank Corrosion Survey",
    date: new Date("2024-08-05"),
  },
];

const training = [
  {
    title: "ASNT Level I & II Radiographic Testing (RT) Course",
    courseDescription: "Comprehensive training course covering the principles, techniques and interpretation of Radiographic Testing per ASNT SNT-TC-1A guidelines.",
    details: "Covers radiation physics, exposure techniques, film/digital interpretation, safety, and applicable codes and standards. Includes hands-on practical sessions with X-Ray and Gamma Ray equipment.",
    schedule: "Batches run quarterly — contact BIX for the next available date.",
    duration: "10 Days",
    certificationInfo: "Certificate issued upon successful completion of written and practical examination, aligned with ASNT requirements.",
    contactInfo: "faiz@bixndt.com | +8801712519316",
  },
  {
    title: "Ultrasonic Testing (UT) & Phased Array (PAUT) Training",
    courseDescription: "Training program covering both conventional Ultrasonic Testing and advanced Phased Array Ultrasonic Testing techniques.",
    details: "Includes probe theory, calibration, scanning techniques, defect sizing, and hands-on operation of OMNISCAN SX and PRISMA phased array instruments.",
    schedule: "Batches run quarterly — contact BIX for the next available date.",
    duration: "12 Days",
    certificationInfo: "Certificate issued upon successful completion of written and practical examination.",
    contactInfo: "faiz@bixndt.com | +8801712519316",
  },
  {
    title: "Magnetic Particle (MT) & Dye Penetrant (PT) Testing Course",
    courseDescription: "Foundational training in Magnetic Particle Inspection and Dye Penetrant Testing methods for surface and near-surface flaw detection.",
    details: "Covers magnetization techniques, particle application, penetrant dwell times, developer application, and indication interpretation.",
    schedule: "Batches run quarterly — contact BIX for the next available date.",
    duration: "7 Days",
    certificationInfo: "Certificate issued upon successful completion of written and practical examination.",
    contactInfo: "faiz@bixndt.com | +8801712519316",
  },
];

module.exports = { services, equipment, projects, gallery, training };
